application: yournametestapp
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico


- url: /prefs
  script: prefs.py
  login: required

- url: /.*
  script: main.py
  
libraries:
- name: webapp2
  version: "2.5.2"
